Graylog2/graylog-ansible-role

- defaults/main.yml
- meta/main.yml
- tasks/main.yml
Not everyone wants to install everything on a single machine. These switches allows one to bypass installing the pieces they don't want.
For example, if I just want to install graylog-web:
```yaml
---
dependencies:
- role: graylog.graylog
graylog_install_server: false
graylog_install_mongodb: false
graylog_install_web: true
graylog_install_nginx: false
graylog_install_elasticsearch: false
```
This is the same as the closed #18 but it was late and I didn't realize that while all the tasks for excluded roles were being listed they were also all being skipped.
> Allow Users to Specify What Pieces They Want to Install

- handlers/main.yml
The service graylog-web was merged in the graylog-server in Graylog2
https://github.com/Graylog2/graylog2-web-interface
> Remove handler graylog-web

- meta/main.yml
The nginx installation roles is included unconditionally.
> skipping nginx installation (graylog_install_nginx) does not work

- tasks/setup-Debian.yml
This prevents the Ansible _changed_ state of "Install Graylog server" task when nothing actually changed.
The cache is (forced) updated when a new repo is installed. The OS updates (should) the cache periodically.
> Do not update cache when installing server

- defaults/main.yml
- templates/graylog.server.conf.j2
- templates/graylog.server.elasticsearch.yml.j2
I did the following:
* grabbed /etc/graylog/server/server.conf from the Debian package (version 2.1.1-2) and matched the _graylog.server.conf.j2_ to it.
* removed unused defaults and added the new ones.
* updated _graylog.server.elasticsearch.yml.j2_  since `graylog_elasticsearch_node_name` got replaced by `elasticsearch_node_name_prefix` (see http://docs.graylog.org/en/2.1/pages/upgrade/graylog-2.0.html).
> Update configuration to match version 2.1.1

- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
When the Debian (and Redhat?) package is installed the server is not started.
I triggered this during a test were I removed the package (`apt get remove graylog-server`), whle the configuration was still intact.
The package got installed properly, but the service was not started.
> Start server after installation

- tasks/server.yml
- tests/support/centos7.Dockerfile
/etc/default/graylog-server and /etc/sysconfig/graylog-server serve the same purpose. On Centos7 the first is not read during startup, so I added an action for ansible_os_family == 'RedHat'. The other action for /etc/default is now scoped to ansible_os_family == 'Debian'.
> /etc/sysconfig/graylog-server should hold the startup parameters on RHEL

- README.md
- defaults/main.yml
- meta/main.yml
- tasks/setup-Debian.yml
Hello, 
I have been working to setup graylog2 properly and find that there was some missing and important notes in the README, also I have added an option to install java from openjdk and not from oracle (keeping the default behaviour as it was in the role, then documented on the README too). 
Resume: 
* Added graylog_install_java var
* Added README example to install openjdk instead of Oracle java
* fix issues with ansible 2.2 (Added examples on the README)
* fix issues with elasticsearch version, explicit set the es version and java version (Documented missing information in the README about graylog incompatibility with elasticsearch 5.x)
* fix issues with java version from elasticsearch role (Documented on README)
* added more useful vars when you are explicit with the usage of roles. …
> Get graylog2 and dependencies working properly and well documented

- defaults/main.yml
- templates/graylog.server.conf.j2
Allow changing `trusted_proxies` in server.conf using new variable `graylog_trusted_proxies` which defaults to empty (leaving the line commented in config). Tested with Ansible 2.2.
> Variablize trusted_proxies in graylog.server.conf

- README.md
Graylog role was not correctly named in "Explicit playbook of roles" section.
> Graylog role was not correctly named in "Explicit playbook of roles" 

- .travis.yml
- README.md
- requirements.yml
- tests/graylog.yml
- tests/support/centos7_21.Dockerfile
- tests/support/centos7_22.Dockerfile
- tests/support/trusty_21.Dockerfile
- tests/support/trusty_22.Dockerfile
- tests/support/wheezy_21.Dockerfile
- tests/support/wheezy_22.Dockerfile
- tests/support/xenial_21.Dockerfile
- tests/support/xenial_22.Dockerfile
Ansible 2.2 should be the main target version of this role. This PR:
* Updates the dependencies to work with 2.2
* Separates the test suite into 2.1 and 2.2 tests to simplify debugging of version issues
* Limit the test suite to only test this role for idempotency (we can not garanty the same for dependencies)
* Mark 2.2.1 and 2.1.2 as supported versions in the README
> Update requirements for Ansible 2.2

- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
When you force the server's package version, the playbook tests if the `graylog_server_version` variable is defined but the `graylog_version` is used.
Here is a small fix for this.
Tested on graylog-server 2.2.2-1 on Ubuntu.
> Fix server package version

- defaults/main.yml
- tasks/setup-Debian.yml
- templates/apt_preferences.d/debian_elasticsearch.j2
This will ensure elasticsearch will not upgrade even when some other role (like logstash) added 5.x repository of elasticsearch. 
It's possible in this way to safetly install logstash with graylog to add more inputs to graylog.
> added Pin priority for elasticsearch to 2.* to avoid upgrades to 5.x version of elasticsearch

- tasks/setup-Debian.yml
`add-apt-repository`, provided by python-software-properties for Debian < 9 and by software-properties-common on Debian 9, is not used anywhere.
This task was useless and made the role incompatible with Debian 9.
> Remove useless package

- defaults/main.yml
- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
In some environments you can't access external repositories, so you have to use a local mirror instead. This adds the possibility to not use the default rpm/deb repo and manage it externally, by setting graylog_manage_(yum|apt)_repo to False.
> Adds a switch to enable/disable repository management

- .gitignore
- .travis.yml
- README.md
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- requirements.yml
- tasks/java-Debian.yml
- tasks/java-RedHat.yml
- tasks/main.yml
- tasks/mongodb-Debian.yml
- tasks/mongodb-RedHat.yml
- tasks/server.yml
- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
- tests/graylog.yml
- tests/support/jessie_22.Dockerfile
- vars/Debian.yml
- vars/RedHat.yml
- vars/main.yml
Hi,
when having a look at the role I noticed a few things, which inconvenienced me.
While most of these are (also) personal preference, I tried to align with the YAML standard as much as possible.
Furthermore, this PR also includes minor documentation and CI changes, which came up in the meantime, e.g. wrong Debian version, some wrong strings in README, etc.
I wanted to get this PR "out of the way", before changing more fundamental things like making the storage directory configurable, etc.
For reviewing, I advice to look at each commit separately.
> Cleanups & documentation

- defaults/main.yml
- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
Variablized graylog install state instead of hard coding `present` to support users who need/want to upgrade their graylog versions.
> variablized graylog install state to support upgrades

- README.md
Hey thanks for the Ansible playbook here.  When attempting to execute the example provided on the README page it seems there is an unnecessary comma within the YAML playbook syntax.
This comma ends up getting inserted into an Elasticsearch configuration file, and in turn causes Elasticsearch to choke when starting up with an error like below:
> java.lang.IllegalArgumentException: Failed to parse value [True,] cannot be parsed to boolean [ true/1/on/yes OR false/0/off/no ]
You'll know you're having the issue when you execute the sample playbook and it will hang on the task for:
> TASK [elastic.elasticsearch : Wait for elasticsearch to startup]
Removing the comma from the playbook seemed to resolve the issue for me. Hope this helps someone else.
> Modified the example playbook in the README to fix ES startup errors

- tasks/server.yml
The task _Wait for Graylog server to startup_ should be more dynamic and allow for testing URI other than localhost. This PR enables waiting for the `graylog_web_listen_uri` to become active.
> Testing should be made dynamic

- requirements.yml
Fixes:
| `ERROR! 'always_run' is not a valid attribute for a Handler
Closes: #94
> Raise dependency on jdauphant.nginx to latest upstream version v2.21.2

- tasks/main.yml
In ansible v2.5 "version_compare" was renamed to "version",
and since ansible v2.9 it has been removed and therefore fails,
also see https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html
> Support ansible >=2.9: version_compare is deprecated

- tasks/mongodb-RedHat.yml
- tasks/setup-Debian.yml
State 'installed' is no longer supported as of ansible v2.9, adjust accordingly.
> Support ansible >=2.9: state 'installed' is deprecated

- tests/support/jessie_22.Dockerfile
The CI job fails when trying to build the Debian Jessie Docker image. 
https://travis-ci.org/github/Graylog2/graylog-ansible-role/jobs/709374454
```
Downloading/unpacking setuptools from https://files.pythonhosted.org/packages/2f/8e/38259f4a44944a92068d5ff77230511a4c685604b47a81318f9e5cf2cc24/setuptools-49.2.0.zip#sha256=afe9e81fee0270d3f60d52608549cc8ec4c46dada8c95640c1a00160f577acf2
Running setup.py (path:/tmp/pip-build-Jej3Q2/setuptools/setup.py) egg_info for package setuptools
Traceback (most recent call last):
File "<string>", line 3, in <module>
File "setuptools/__init__.py", line 21, in <module>
import setuptools.version
File "setuptools/version.py", line 1, in <module>
import pkg_resources
File "pkg_resources/__init__.py", line 1380
raise SyntaxError(e) from e
^
SyntaxError: …
```
> Fix python setuptools install failure.

- defaults/main.yml
Graylog 3.1.0 was released on 2019-08-16 and nowadays we're at version 3.1.3
(released on 2019-11-06).
> Upgrade default version to Graylog v3.1

- defaults/main.yml
- templates/graylog.server.conf.j2
- tests/graylog.yml
Currently there is no way to add in configuration for any of the plugins. For example a [data reporter](https://github.com/graylog-labs/graylog-plugin-metrics-reporter/blob/master/metrics-reporter-datadog/README.md) requires configuration that is not able to get set with this role. This PR adds in the ability to add arbitrary `key = value` to the configuration file
> add in ability to supply arbitrary key/values for server config

- tasks/server.yml
When using different directory paths, the graylog-server service is failed.
> Make sure graylog-server directories exist

- .travis.yml
- README.md
- defaults/main.yml
- meta/main.yml
- molecule/default/converge.yml
- molecule/default/molecule.yml
- requirements.yml
- tasks/install-java.yml
- tasks/main.yml
- tasks/mongodb-Debian.yml
- tasks/mongodb-RedHat.yml
- tasks/server.yml
- templates/mongodb.conf.j2
- vars/RedHat.yml
Currently, the test playbook just installs Graylog. Ideally, it should start up Elasticsearch, Mongodb, and Graylog and ensure they start correctly.
> Various test enhancements

- .travis.yml
- molecule/default/molecule.yml
- molecule/default/verify.yml
Fixing this error in Travis CI:
```
--> Scenario: 'default'
--> Action: 'verify'
--> Executing Testinfra tests found in /home/travis/build/Graylog2/graylog-ansible-role/molecule/default/tests/...
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --ansible-inventory=/home/travis/.cache/molecule/graylog-ansible-role/default/inventory/ansible_inventory.yml --connection=ansible
inifile: None
rootdir: /home/travis/build/Graylog2/graylog-ansible-role/molecule/default
```
https://travis-ci.org/github/Graylog2/graylog-ansible-role/jobs/711097325
> Attempt to fix service tests.

- README.md
- defaults/main.yml
- meta/main.yml
- molecule/default/converge.yml
- tasks/main.yml
- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
Making the `graylog_version` variable required, so that people can opt-in to the Graylog version they want. Otherwise, when we update the default value, we might break installs. 
Also updated the docs a bit.
> Make graylog_server var required.

- README.md
- defaults/main.yml
- molecule/default/converge.yml
- tasks/main.yml
The version of MongoDB should be configurable, not hardcoded. At the same time, I am wary of surprise-updating someone's MongoDB instance. I think it should be opt-in, so people can upgrade when they want and ensure they are ready for it. The user should tell us what version of MongoDB they want.
This will make it so that if someones specifies `graylog_install_mongodb: True`, then they will also need to specify `graylog_mongodb_version` and the key for the package repo. If they specify `graylog_install_mongodb: False`, then nothing will change, as the code will be ignored.
> Make Mongodb version configurable.

- tasks/setup-Debian.yml
This would resolve https://github.com/Graylog2/graylog-ansible-role/issues/74
> Add version to graylog tmp repository file

- defaults/main.yml
- tasks/mongodb-Debian.yml
- tasks/mongodb-RedHat.yml
- templates/mongodb.conf.j2
Theres not much more to add. Default behaviour remains the same.
> Make MongoDB IP and port binding configurable

- molecule/default/tests/test_default.py
- templates/mongodb.conf.j2
Hi,
The role currently deploys a mongodb.conf file which does not work on CentOS or any other RedHat derivatives, nor on RedHat itself.
In this PR mongodb.conf's template have been updated with matching configuration from the original rpm config file to ensure that the role works on RedHat (and derivatives) as well.
[https://github.com/mongodb/mongo/blob/master/rpm/mongod.conf#L21]()
Thanks,
Frank
> Updating mongodb.conf template to make it work on RedHat derivatives as well

- tasks/main.yml
- tasks/server.yml
To facilitate the use of the role to push just
configuration changes tags are added at the
appropriate locations.
I don't know if there are some ansible community internal default "tags" for a use case like this.
Maybe graylog_configuration would be a better name for the tag?
> Add configuration tag

- defaults/main.yml
Allows to add extra variables to the JAVA_OPTS
string, without missing upstream updates.
> Add graylog_server_java_opts_extra

- README.md
- defaults/main.yml
- meta/main.yml
- molecule/default/converge.yml
- molecule/ui/converge.yml
- requirements.yml
- tasks/main.yml
Remove Nginx role dependency, as it's been abandoned and no longer works. Adding documentation instructing users to include the official Nginx role if they need it. Also added a check to throw an error if a user has `graylog_install_nginx` set to `True`. If they have it set to `False`, it will continue as normal.
Fixes #144
> Remove Nginx dependency

- defaults/main.yml
- templates/graylog.server.default.j2
Allow the Graylog server 'JAVA' environment variable to be customized
using a `graylog_server_java` role variable. The value defaults to
`/usr/bin/java`, which is the existing behavior. This helps use the role
in cases where `/usr/bin/java` is not the desired java executable.
> Expose Java path as variable

- README.md
- molecule/example2/converge.yml
- molecule/example2/molecule.yml
Adding an example playbook to demonstrate a cluster install. 
**Testing the playbook**
```
virtualenv venv
source venv/bin/activate
python3 -m pip install -U pip
pip3 install -r requirements.txt
molecule create --scenario-name=example2
molecule converge --scenario-name=example2
molecule list
molecule login --scenario-name=example2 -h graylog01
```
Fixes #89 
Reference:
- https://docs.graylog.org/v1/docs/multinode-setup
> Add cluster example playbook

- defaults/main.yml
- templates/graylog.server.conf.j2
Hi, there. 
I noticed a lack of configuration in templates/graylog.server.conf.j2. So I propose this configuration when I referenced  [[git.codificar.com.br/diogo.coutinho] this config](https://git.codificar.com.br/diogo.coutinho/laradock-multi-projetos/blob/master/graylog/config/graylog.conf).
Detail; The add settings are not contained the template of graylog.server.conf.j2 whether contained the default config parameter [defaults/main.yml#L120-L123](https://github.com/Graylog2/graylog-ansible-role/blob/648669639d995478d916e60c609d49bc5d983b58/defaults/main.yml#L120-L123).
My Graylog version is 4.2. If it needs to consider under the 3.0 version for lower compatibility, Let me know it. And if you have some idea, could you tell me it?
>  [+] Add a initial content pack settings

- defaults/main.yml
- tasks/setup-Debian.yml
- tasks/setup-RedHat.yml
- templates/graylog.server.default.j2
Integration of new packaging with the usage of booleans for open and enterprise package. Methods make graylog_full_version no longer optional.
Make the usage of the bundled jdk version possible with leaving the java-home enviroment binary path empty.
> Integrate new packaging into the role and usage of bundled openjdk
